# xAILab
# Chair of Explainable Machine Learning
# Otto-Friedrich University of Bamberg
#
# Parameter configurations for training and evaluation.

# Fixed Parameters
data_path: ''  # Where the dataset is stored
output_path: ''  # Where the trained model shall be stored.
epochs: 100  # How many epochs to train for.
learning_rate: 0.0001  # Learning rate
batch_size: 64  # Batch size for the training.
batch_size_eval: 256  # Batch size for the evaluation.
device: 'cuda:0'  # Which device to run the computations on.

# Modifiable Parameters
dataset: 'bloodmnist'  # Which dataset to use. ('bloodmnist', 'breastmnist', 'chestmnist', 'dermamnist', 'octmnist', 'organamnist', 'organcmnist', 'organsmnist', 'pathmnist', 'pneumoniamnist', 'retinamnist', 'tissuemnist')
img_size: 28  # Height and width of the input image. (28, 64, 128, 224)
training_procedure: 'endToEnd'  # Which training procedure to use. ('endToEnd', 'linearProbing', 'kNN')
architecture: 'vgg16'  # Which model to use. ('vgg16', 'alexnet', 'resnet18', 'densenet121', 'efficientnet_b4', 'vit_base_patch16_224', 'vit_base_patch16_clip_224', 'eva02_base_patch16_clip_224', 'vit_base_patch16_224.dino', 'samvit_base_patch16')
k: 11  # Number of neighbors for the kNN.
seed: 9930641  # Seed for random operations for reproducibility. (9930641, 115149041, 252139603)